name: Build package to proof validity
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build package
        run: mvn install
      - name: Test package
        run: mvn test